[package]
name = "rl_ball_sym_pybinds"
version = "2.0.5"
edition = "2021"
rust-version = "1.73"
license = "MIT"
publish = false
exclude = [".github/", "*.bat", "*.sh", ".git*", "*.py", "*.png", "rustfmt.toml", "*.cfg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies.rl_ball_sym]
# version = "4.0.0"
default-features = false
features = ["compression", "standard", "hoops", "dropshot", "throwback"]
path = "../rl_ball_sym"

[dependencies.pyo3]
version = "0.20.0"
features = ["extension-module", "abi3-py37"]

[profile.release]
codegen-units=1
lto = true
strip = true
panic = "abort"
