[package]
name = "rl_ball_sym_pybinds"
version = "1.0.7"
edition = "2021"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
rl_ball_sym = "2.1"

[dependencies.pyo3]
version = "0.17.1"
features = ["extension-module", "abi3-py37"]

[profile.release]
codegen-units=1
lto = "fat"
panic = "abort"
strip = true
