[package]
name = "rl_ball_sym_pybinds"
version = "1.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
glam = "0.21.2"
rl_ball_sym = "2.0.0"
lazy_static = "1.4"

[dependencies.pyo3]
version = "0.16"
features = ["extension-module"]

[profile.release]
codegen-units=1
lto = "fat"
panic = "abort"
